### ISSUE TITLE
List object has no attribute 'cursor' 

### ISSUE THREAD

**Issue by darkhacknet** [MatMasIt/sqlGram#1]
Hello,  as you can see Im favlcin this issue,  everything seems to be ok but when I just send any command, the error is displayed.

Here you have a SS. Would you be so kind to help me, solving this?

Thanks in advance. ![IMG_20220821_043112.jpg](https://user-images.githubusercontent.com/45680149/185784833-c3f190d2-d80d-44aa-b82c-4c5d8fb10c97.jpg)

**Comment by MatMasIt** [comment]
Hi, can you pull the changes I made, try again and post the exception backtrace?
Thanks

**Comment by darkhacknet** [comment]
> Hi, can you pull the changes I made, try again and post the exception backtrace? Thanks

Heloo bro thanks for the prompt response, now Im having issues with the connection to localhost, it said connection refused, so  please wait while I try to fix it and then I will post the backtrace.

**Comment by darkhacknet** [comment]
> Hi, can you pull the changes I made, try again and post the exception backtrace? Thanks

Bro hope you are well, you can close this one, now everything is working fine, I think that it iwas an error in my db connection port. So now I have no errors. Thank you so much for this, Its all what I need to add users and credits to the users of my bots.

**Comment by MatMasIt** [comment]
Wow, thanks, I am surprised somebody was still using this
